import sys
import math

def main():
    with  open("../irradiance") as f:
        for line in f:
            values = line.split("\t")
            res = mean_cf(float(values[0]), float(values[1]))
            print res[0], "\t", res[1]
    
def mean_cf(PV_Plant_high,PV_Plant_low):
 PV_Capacity = 30; #(kW) size of PV array
 Panel_Rating = 0.327; #(kW) rated E20-327 Sunpower Panel
 Avg_CA_Res = 16.4 ; # %CF
 Avg_CA_Com = 17.4 ; # %CF
 Avg_CA_Utility = 21.0 ; # %CF

 Panel_Eff = 0.201; # Efficiency of panel
 PV_Area = 1.046*1.559; # (m^2) area per panel
 PV_Weight = 21.6+10; # (Kg) weight per panel plus 10 kg for simple support
 Panel_Number=math.ceil(PV_Capacity/Panel_Rating); # Rounding up to the number of panel needed for system
 Energy_PV_high = Panel_Number*PV_Area*Panel_Eff*PV_Plant_high*8760/1000; # (kWh) Generated by panels per year
 Energy_PV_low = Panel_Number*PV_Area*Panel_Eff*PV_Plant_low*8760/1000; # (kWh) Generated by panels per year

 CF_PV_Utility_high = Energy_PV_high/(8760*Panel_Rating*Panel_Number) # The capacity factor for solar for each location in world
 CF_PV_Utility_low = Energy_PV_low/(8760*Panel_Rating*Panel_Number) # The capacity factor for solar for each location in world

 CF_PV_Res_high=CF_PV_Utility_high*(Avg_CA_Res/Avg_CA_Utility)
 CF_PV_Res_low=CF_PV_Utility_low*(Avg_CA_Res/Avg_CA_Utility)

 CF_PV_Com_high=CF_PV_Utility_high*(Avg_CA_Com/Avg_CA_Utility)
 CF_PV_Com_low=CF_PV_Utility_low*(Avg_CA_Com/Avg_CA_Utility)

 return (CF_PV_Utility_low,CF_PV_Utility_high) 

if __name__ == "__main__":
    sys.exit(main())